#!/usr/bin/env bash
# gpu-mode.sh — list GPUs and toggle single vs. multi-GPU mode for llm-test-bench.
#
# Writes .gpu-mode (gitignored) which is sourced by run.sh before calling bench.py.
# In single-GPU mode bench.py strips tensor_split and sets CUDA_VISIBLE_DEVICES so
# llama-server only sees one card.  run.sh also exports CUDA_VISIBLE_DEVICES so vLLM
# and ollama backends respect the setting automatically.
#
# Usage:
#   ./gpu-mode.sh                  show current mode and GPU list
#   ./gpu-mode.sh toggle           toggle between single (GPU 0) and multi
#   ./gpu-mode.sh single [INDEX]   use only GPU INDEX (default: 0)
#   ./gpu-mode.sh multi            use all GPUs (default behaviour)
#
# Note: vLLM with tensor_parallel_size > 1 will fail in single-GPU mode — update the
# .vllm model file to tensor_parallel_size=1 when using single-GPU mode with vLLM.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE_FILE="$SCRIPT_DIR/.gpu-mode"

# ── Read current config ────────────────────────────────────────────────────────
GPU_SINGLE_INDEX=-1
if [[ -f "$MODE_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$MODE_FILE"
fi

# ── Detect GPUs ────────────────────────────────────────────────────────────────
if ! command -v nvidia-smi &>/dev/null; then
    echo "ERROR: nvidia-smi not found — cannot detect GPUs" >&2
    exit 1
fi

GPU_INFO=$(nvidia-smi --query-gpu=index,name,memory.total \
    --format=csv,noheader,nounits 2>/dev/null || true)
GPU_COUNT=$(echo "$GPU_INFO" | grep -c '[^[:space:]]' || true)

if [[ "$GPU_COUNT" -eq 0 ]]; then
    echo "ERROR: no GPUs detected by nvidia-smi" >&2
    exit 1
fi

# ── Helpers ────────────────────────────────────────────────────────────────────
_show_gpus() {
    echo "GPUs detected ($GPU_COUNT):"
    while IFS=',' read -r idx name mem_mib; do
        idx="${idx// /}"
        name="${name# }"
        mem_mib="${mem_mib// /}"
        mem_gb=$(( (mem_mib + 512) / 1024 ))
        printf "  [%s] %s  (%d GB)\n" "$idx" "$name" "$mem_gb"
    done <<< "$GPU_INFO"
}

_show_mode() {
    echo ""
    if [[ "$GPU_SINGLE_INDEX" -ge 0 ]]; then
        echo "Current mode: single GPU [${GPU_SINGLE_INDEX}]"
        echo "  CUDA_VISIBLE_DEVICES=${GPU_SINGLE_INDEX}"
        echo "  tensor_split disabled (stripped by bench.py)"
    else
        echo "Current mode: multi GPU (all ${GPU_COUNT} GPUs)"
        echo "  tensor_split from model file is active"
    fi
}

_write_mode() {
    local idx=$1
    cat > "$MODE_FILE" <<EOF
# Generated by gpu-mode.sh — do not edit manually.
# Sourced by run.sh before bench.py. -1 = all GPUs; >= 0 = single GPU index.
GPU_SINGLE_INDEX=${idx}
EOF
    echo "Saved: $MODE_FILE  (GPU_SINGLE_INDEX=${idx})"
}

# ── Command dispatch ────────────────────────────────────────────────────────────
CMD="${1:-show}"

case "$CMD" in
    show|status)
        _show_gpus
        _show_mode
        ;;

    toggle)
        _show_gpus
        if [[ "$GPU_SINGLE_INDEX" -ge 0 ]]; then
            _write_mode -1
            echo "Mode: → multi GPU (all ${GPU_COUNT} GPUs)"
        else
            _write_mode 0
            echo "Mode: → single GPU [0]"
        fi
        ;;

    single)
        IDX="${2:-0}"
        if ! [[ "$IDX" =~ ^[0-9]+$ ]]; then
            echo "ERROR: INDEX must be a non-negative integer, got: ${IDX}" >&2
            exit 1
        fi
        if [[ "$IDX" -ge "$GPU_COUNT" ]]; then
            echo "ERROR: GPU index ${IDX} out of range (0–$((GPU_COUNT - 1)))" >&2
            exit 1
        fi
        _show_gpus
        _write_mode "$IDX"
        echo "Mode: → single GPU [${IDX}]"
        ;;

    multi)
        _show_gpus
        _write_mode -1
        echo "Mode: → multi GPU (all ${GPU_COUNT} GPUs)"
        ;;

    -h|--help|help)
        cat <<'EOF'
Usage: ./gpu-mode.sh [COMMAND] [INDEX]

Commands:
  show              show GPU list and current mode  (default)
  toggle            switch between single [0] and multi
  single [INDEX]    use only GPU INDEX (default: 0)
  multi             use all GPUs

Examples:
  ./gpu-mode.sh               # show status
  ./gpu-mode.sh toggle        # switch mode
  ./gpu-mode.sh single        # use GPU 0 only
  ./gpu-mode.sh single 1      # use GPU 1 only
  ./gpu-mode.sh multi         # use all GPUs
EOF
        ;;

    *)
        echo "ERROR: unknown command '${CMD}'. Run ./gpu-mode.sh --help" >&2
        exit 1
        ;;
esac
